# Generated by Django 5.0.3 on 2024-03-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=15),
        ),
    ]
